export const PATHWAYS = [
  'ADHD',
  'Alcohol',
  'Anger',
  'Anxiety',
  'Benzodiazepines',
  'Cancer Care',
  'Cannabis',
  'Cardiac Care',
  'Career',
  'Depression',
  'Diabetes',
  'Digestive Health',
  'Eye Care',
  'Fertility Care',
  'Financial Wellbeing',
  'Fitness',
  'Foundational Therapy',
  'General Health',
  'Grief',
  'Hypertension',
  'Kidney Care',
  'Leadership',
  'Lung Care',
  'Maternity',
  'MDMA',
  'Mindfulness',
  'Nutrition & Yoga',
  'OCD',
  'Opioids',
  'Other Concerns',
  'PCOS',
  'Postpartum',
  'PTSD',
  'Relationships',
  'Sleep',
  'Smoking',
  'Stimulants',
  'Stress',
  'Weight Gain',
  'Weight Loss',
  'Work Performance'
];
