server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location /client_tasks/ {
        rewrite ^/client_tasks/(.*) /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location /client_tasks {
        rewrite ^/client_tasks$ /index.html break;
        rewrite ^/client_tasks/(.*) /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
